# Site settings
encoding: utf-8
title: study

email: "kyowoon.lee1924@gmail.com"
url: "http://leekwoon.github.io"
github_url: "http://github.com/leekwoon/study"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/leekwoon"
baseurl: "/study"
disqus_shortname: leekwoon


exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
